# This is a basic workflow to help you get started with Actions

name: Haxe

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        haxe-version: ["1:4.2.5-1~ubuntu22.04.1~ppa1"]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install haxe
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install haxe=${{matrix.haxe-version}} -y
      
      - name: Setup haxelib
        run: haxelib setup ~/haxe/lib

      - name: Install libraries
        run: haxelib install hxcpp
      
      - name: Build app
        run: haxe build.hxml
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: escam
          path: ./bin/Main
